# Generated by Django 5.1.6 on 2025-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_countrys',
            field=models.ManyToManyField(to='book_outlet.country'),
        ),
    ]
